### ISSUE TITLE
Resetting the control after usage

### ISSUE THREAD

**Issue by mattjameswdd** [radify/angular-file#4]
I've got a page for managing users, and they need to be able to upload profile images.  Because of the way the page is designed, I re-use the same form and controls for each add/edit operation.  Is there any way to reset the control back to the default after each save operation?  I've tried clearing the ng-model bound variable and removing the file from the base file control.  Neither have the affect that I expected.  Thoughts?

**Comment by nateabele** [comment]
I don't know how to answer because I can't see the template expression (I'm assuming) that `staff-matt.png` comes from.

Assuming it comes from a `File` object, which can't be modified for aforementioned security reasons, your best approach would be to just `delete` the object from wherever it's bound to on your scope.

Hope that helps. Beyond that, this is more of a generic DOM/data access issue, for which you'd probably get quicker answers on StackOverflow.
